<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 20 Sep 2020 16:41:40 +0000
 */
$conf['title'] = 'SNES';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['disableactions'] = 'register';
